### ISSUE TITLE
Can't use ES6 promise with mpromise style constructor

### ISSUE THREAD

**Issue by arcs-** [boblauer/cachegoose#10]
With the latest version of mongoose, they'll tell you to switch to another promise library ( the one they use "mpromise" is decrapricateted ).

It seems Cachehoose doesn' support this currently and when I switched to the ES6 varriant I got ("Can't use ES6 promise with mpromise style constructor").

**Comment by boblauer** [comment]
Thanks for bringing this to my attention.  Just published the fix to npm, `cachegoose@3.0.0`
