### ISSUE TITLE
MongoDB with cachegoose more slow

### ISSUE THREAD

**Issue by marcusmota** [boblauer/cachegoose#13]
Do you guys have any idea why with cachegoose i got the inverse result ?

with cachegoose my result is in 1.2s  (always)
without cachegoose my result is in 0.6s

on redis-cli keys *
127.0.0.1:6379> keys *
1) "cacheman:cachegoose-cache:2d2c760092875c462a88cd491ece39e3e6651773"
2) "cacheman:cachegoose-cache:categories"

    model.find({}).cache(0, 'categories').exec(function (err, resp) {
        res.send(resp);
    });

Thanks

**Comment by boblauer** [comment]
It's very possible that if you're just grabbing every single record without filtering anything out, Mongo is faster.  The benefit of using cachegoose is to cache complicated queries that take Mongo a long time to determine which records to return, but caching an entire collection (no matter how big or small it is) is not advisable.
