### ISSUE TITLE
Issues with aggregate

### ISSUE THREAD

**Issue by thenitai** [boblauer/cachegoose#16]
I'm having an issue with aggregate and this library. The error I get is:

```
TypeError: Cannot read property 'constructor' of undefined
```

However, the aggregate return records and with this library all works good. Mind you, I did not cache anything or applied any caching to any finds yet. I simply installed this library. It looks like it hooks into aggregate and expects certain results.

**Comment by thenitai** [comment]
For the record, as soon as I changed my syntax to:

```
.aggregate(project).unwind("$registration_dates").group(group).exec(
```

it started to work.

**Comment by boblauer** [comment]
Can you provide the original syntax you were using so I can look into this? Thanks.

**Comment by thenitai** [comment]
Sure thing. Original syntax was:

```
.aggregate(project, unwind, group, callback)
```

**Comment by Daeik** [comment]
@boblauer 
This problem still persists in `cachegoose 4.0.2` with `mongoose 4.11.5`.
I initially used same syntax as @thenitai, which is `Model.aggregate([...stages], callback);` and as soon as I changed the syntax to `Model.aggregate().match().project().exec()` and it started working.

**Comment by niftylettuce** [comment]
Can you re-open this please?
