### ISSUE TITLE
Able to clean cache entry with wildcard

### ISSUE THREAD

**Issue by masterviana** [boblauer/cachegoose#19]
That is not an issue is only a question sorry for open that.

Imagine if I want to get and cache multiple querys from same collection lets says User, for one query i use id:10 and I want select only username and email,  and for id:10 I want to select other fields address and name, for now I'm creating a custom key with filter id:10 concat with select fields and use a hash of that.

cache(10, 'user'+ id+ hash(criteria, select))

and redis keys are : 
"cacheman:cachegoose-cache:user-10-3d7a7cc3c7c227b2dcc75ed62ccd0e166af5a186"
"cacheman:cachegoose-cache:user-10-3d7a7cc3c7c227b2dcc75ed62ccd0e166af5a186"

This two queries are used with differents parts of code and need this different selects, but now for invalidate this object for both objects (with to differents selects querys) but for same id, I want to delete all entries in redis. When I call findAndUpdate for id:10 I want to delete all two entris in redis w

There a way to doing this?  like this  cachegoose.clearCache('user-10-*');

**Comment by boblauer** [comment]
Unfortunately Redis does not have a simple way of deleting keys based on a pattern.  I think I would probably accomplish this by manually calling `clearCache` for both entries, which I know isn't ideal but unfortunately is the only option available right now.

**Comment by mayconmesquita** [comment]
I can do this using this lib: https://github.com/uber-archive/redis-delete-pattern

My code:
```js
const redis = require('redis');
const redisDeletePattern = require('redis-delete-pattern');
const client = redis.createClient();

redisDeletePattern({ redis: client, pattern: 'cacheman:cachegoose-cache:mypattern-*' }, (err, keys) => {
   // ...
});
```

To get the keys using a pattern, we can do:
```js
client.keys('cacheman:cachegoose-cache:*', function (err, keys) {
  // ...
});
```
