### ISSUE TITLE
Cache without schema

### ISSUE THREAD

**Issue by Christilut** [boblauer/cachegoose#21]
Is there a way to apply this directly on a mongodb collection?
```
  const result = await mongoose.connection.db.collection('websites')
    .findOne({
      name,
      _active: true
    })
    .cache(60, 'websiteByName-' + name)
```

I do this because this is a second, very simple, process to only retrieve data from mongo and I don't want to have the same schema in both projects. The main project does use schemas and caching works perfectly fine there.

**Comment by boblauer** [comment]
I don't believe there is a way to do this.  When you access `mongoose.connection.db.collection`, you are dealing with the mongodb node driver, and essentially bypassing mongoose altogether.

This is a bit hacky, but one solution you could consider using is to try accessing the cached data in redis directly, and then falling back to a mongo query if the data is not in redis.

I will also say, if the example you gave above is a real-world query that you want to cache, you may find that you're not getting much of a benefit from caching in redis, if any.  `findOne` should be pretty fast, and should be especially fast if you have an index on `name`.  I suppose it probably depends on how many records are in this collection and what indexes you have, but you may want to play around with it and see if using cachegoose is giving you a benefit at all.

**Comment by Christilut** [comment]
Thanks for the detailed reply. I'll recheck my queries and see if redis is indeed needed here.

I'll see if I can monitor the usage and perhaps implement the hacky solution :)

Thanks!
