### ISSUE TITLE
Q: Does cachegoose remove the keys after inserting, updating and removing?

### ISSUE THREAD

**Issue by albertomr86** [boblauer/cachegoose#23]
Suppose a scenario in which a list is cached for 5 minutes, but before the list expires a new record is inserted. For this case I don't want to get the old list, but a new one with the record in it?
It would be nice to delete all keys belonging to the model where the record was inserted.

**Comment by boblauer** [comment]
This is possible, although it's something you'll have to manage manually.  From the README:

- - - 

You can also pass a custom key into the `.cache()` method, which you can then use later to clear the cached content.

```javascript
var mongoose = require('mongoose');
var cachegoose = require('cachegoose');

cachegoose(mongoose, {
  engine: 'redis',
  port: 6379,
  host: 'localhost'
});

var userId = '1234567890';

Children
  .find({ parentId: userId })
  .cache(0, userId + '-children') /* Will create a redis entry          */
  .exec(function(err, records) {  /* with the key '1234567890-children' */
    ...
  });

ChildrenSchema.post('save', function(child) {
  // Clear the parent's cache, since a new child has been added.
  cachegoose.clearCache(child.parentId + '-children');
});
```

**Comment by albertomr86** [comment]
Thank you. 
Yes I saw it, in that way I have to specify the all keys to remove; but what if, from the same model I have several list cached with different filters; do I have to remove each one? I am more interested in something like:

```javascript
UserSchema.post('save', function(doc) {
   cachegoose.clearCache(doc.baseKey + '*');   // <-- this line
});
```

```javascript
Users
  .find({ active: true })
  .cache(30)     // <--  baseKey + hash
  .exec(function(err, records) {
    ...
  });

Users
  .find({ level: 2 })
  .cache(30)    // <--  baseKey + hash
  .exec(function(err, records) {
    ...
  });
```
```javascript
User.insert({ ...fields });
```

After the insert, both list were removed.

**Comment by boblauer** [comment]
There is no current way to accomplish this.  My worry with introducing something like this is that if you have many keys, doing a redis scan on `doc.baseKey + '*'` could potentially be very slow.

One suggestion would be to move your cache key generation to a library of some sort (or a variable if setting the key and clearing the cache occur in the same file), and then you could grab those same keys in your post-save hook.

```js
const userCacheKeys = require('./user-cache-keys');

UserSchema.post('save', function(doc) {
  cachegoose.clearCache(userCacheKeys.activeUsersKey);
  cachegoose.clearCache(userCacheKeys.level2Key);
});
```

**Comment by albertomr86** [comment]
Understood, thank you!.
