### ISSUE TITLE
Lack of Support for Aggregate Promise Chain

### ISSUE THREAD

**Issue by valeeum** [boblauer/cachegoose#24]
Aggregate method requires callback parameter:  .exec().then(results => {...}) type promise chain is unsupported.

**Comment by boblauer** [comment]
hhmm.  I just wrote this test, which passed:

```js
  it('should cache aggregate queries that use Promises', function (done) {
    aggregate(60)
      .then((res) => {
        Boolean(res._fromCache).should.be.false;
      })
      .then(() => {
        return aggregate(60);
      })
      .then((res) => {
        Boolean(res._fromCache).should.be.true;
      })
      .then(() => done())
      .catch(done);
  });
```

This confirms that aggregate promise chains are supported.  I wonder if you're seeing some other issue?

**Comment by valeeum** [comment]
what is the significance of passing in the parameter of 60?  shouldn't aggregate take an array as a parameter and call .exec() to return a promise?  something like so?  

`someSchema.aggregate([{$group: {_id:null, count: {$sum: 1} }}]).exec().then(res => console.info(res)) `

**Comment by boblauer** [comment]
Yeah sorry, you'll need to look at the test file in the project to see the implementation of the `aggregate` function.
