### ISSUE TITLE
Caching the result of count()

### ISSUE THREAD

**Issue by tomkelsey** [boblauer/cachegoose#25]
Hey,

Thanks for making cachegoose - looks to be (almost - I think) exactly what I'm after!

I wanted to double check I wasn't missing something - I'm attempting to cache the result of a `count()` operation - e.g. `Document.count({ filter }).cache(60).exec()`

I've had a skim through the code and I don't believe cachegoose caches `count()` at the moment? If I can get my head around it, would you be open to a PR that added support for it?

Thanks

**Comment by boblauer** [comment]
It was fairly easy to implement, so I went ahead and added it myself.  Publish `@3.1.2`.

Thanks for the issue!

**Comment by tomkelsey** [comment]
Excellent, thanks a lot 👍
