### ISSUE TITLE
Cache key doesn't factor in sort?

### ISSUE THREAD

**Issue by tomkelsey** [boblauer/cachegoose#27]
Hi again :)

I noticed a bug in my application after implementing cachegoose and I believe it might be because the code to generate the cache key:

```
const key = {
      model: this.model.modelName,
      op: this.op,
      skip: this.options.skip,
      limit: this.options.limit,
      _options: this._mongooseOptions,
      _conditions: this._conditions,
      _fields: this._fields,
      _path: this._path,
      _distinct: this._distinct
    };
```

doesn't factor in `sort()`?

So two queries that are the same, but for the sort order, would generate the same cache key even though the result set would be different?

**Comment by boblauer** [comment]
You are correct.  Thanks for the issue, fixed and published `@4.0.1`
