### ISSUE TITLE
Any plans on chaching caching engine?

### ISSUE THREAD

**Issue by thenitai** [boblauer/cachegoose#28]
Hi,

We use your tool all over. Thank you again for the work.

One question, could we potentially use MongoDB also as a cache engine in addition to Redis? Our experience with Redis cluster is rather sub-par and we would like to setup another MongoDB server for caching.

**Comment by boblauer** [comment]
`cachegoose` is setup to use any `cacheman` engine, so it already has support for Mongo.

https://github.com/cayasso/cacheman#api

Specifically, it would look something like this (this is untested, but should be mostly correct):

```js
var mongoose = require('mongoose');
var MongoEngine = require('cacheman-mongo');
var cachegoose = require('cachegoose');

cachegoose(mongoose, {
  engine: new MongoEngine()
});
```

**Comment by thenitai** [comment]
The wording of my question was wrong.

I thought it would support it, was just unsure because I did not see any
example other than seeing that the module uses cacheman.

I'll try and reportback.

Thank you

**Comment by thenitai** [comment]
As a followup:

We converted everything to Mongodb now. However, I believe there are some issues with the cacheman-mongo library. Some settings, even though outlines in the example, seem to not work. 

Furthermore, and what seems to be more strange, is that the cacheman-mongo library creates an index with a timeout of "0" (zero) seconds. Hence, even though we would set a TTL of, e.g. 90 seconds, the record is deleted in the collection already.

Not sure why or the reason for this...

**Comment by boblauer** [comment]
Closing, as this sounds like an issue with `cacheman-mongo` and not with this library.
