### ISSUE TITLE
Is it necessary to have a build?

### ISSUE THREAD

**Issue by zacharynevin** [boblauer/cachegoose#3]
Why is it that this needs to have a build when installing? It seems that the files can be rewritten such that a build is not needed at all. I imagine this would make it difficult to integrate in places like Heroku since the build script for this repo doesn't seem run automatically on installation.

**Comment by zacharynevin** [comment]
It seems that I am the only one having this issue

**Comment by zacharynevin** [comment]
I'm using windows - that's likely why I was having issues

**Comment by boblauer** [comment]
Were you able to get this resolved?

**Comment by zacharynevin** [comment]
I wasn't on my end. I had to manually run the build.

Is the build supposed to run automatically when you install the package?

**Comment by boblauer** [comment]
I thought it would, but it doesn't.  I have updated the package to include the actual built javascript, and verified that you can now use it without having to install anything.

Thanks for bringing that to my attention, I had no idea it was an issue.

**Comment by zacharynevin** [comment]
Perfect, thank you!
