### ISSUE TITLE
Improve mongoose version comparison

### ISSUE THREAD

**Issue by LouisTakePILLz** [boblauer/cachegoose#32]
The [mongoose version compatibility check][1] compares **strings** by [type coercion](https://stackoverflow.com/questions/6712947/javascript-string-to-number-type-coercion) (i.e. by implicitly converting them to decimal numbers).

`String`-to-`Number` type coercion shouldn't be used (or at least never for comparing versions) since it fails for double-digit minor versions, e.g.
```js
// Source
if (mongoose.version < '3.7') {
  throw new Error('Cachegoose is only compatible with mongoose 3.7+');
}
// Tests
if ('3.10' < '3.7') // false even though 3.10 is more recent than 3.7
if ('3.7.1' < '3.7') // false even though 3.7.1 is more recent than 3.7
```

Proposed fix
---------------

Use [compare-versions](https://github.com/omichelsen/compare-versions)

e.g.
```js
const compareVersions = require('compare-versions');

if (compareVersions(mongoose.version, '3.7') < 0) {
  throw new Error('Cachegoose is only compatible with mongoose 3.7+');
}
```

[1]: https://github.com/boblauer/cachegoose/blob/69abfbcfd796c44bbffc4e85846f64cfc6fbde98/src/index.js#L7

**Comment by boblauer** [comment]
Thanks for the heads up. This has been fixed and published, `@6.0.0`.

**Comment by LouisTakePILLz** [comment]
Awesome!

**Comment by LouisTakePILLz** [comment]
Now that I think of it, you could drop the runtime check altogether and replace it with a peerDependency version check. Less code and npm does the job for you.

The only difference is that they get a warning (as opposed to throwing an error) upon installing the plugin.

Something like this:

```js
// package.json
"peerDependencies": {
  "mongoose": ">= 3.7"
}
```

Sorry for the bother, not sure why I didn't think of it sooner.
