### ISSUE TITLE
Add typings declarations for Typescript

### ISSUE THREAD

**Issue by santiq** [boblauer/cachegoose#38]
Hello!

For typescript projects, it would be nice if this library provides its official declaration files.

Here are some guides on how to write them

http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

http://blog.wolksoftware.com/contributing-to-definitelytyped

**Comment by boblauer** [comment]
I don't personally use TypeScript, but I would be happy to accept a pull request.
