### ISSUE TITLE
Wrong caching when use $regex

### ISSUE THREAD

**Issue by SerjoPepper** [boblauer/cachegoose#4]
I have inconsistent results when using $regex in query

**Comment by boblauer** [comment]
Can you expand upon that?  And ideally, give me a simple example that reproduces the problem?

**Comment by SerjoPepper** [comment]
I try to explain. When you generate key for redis, you use JSON.stringify() and sha1. JSON.stringify of {a: /myrgx/i} returns {a: {}}. So all request with difference regexps will be chached in one redis key. But if you use String(/myrgx/i) it will return '/myrgxp/i'

**Comment by boblauer** [comment]
Thanks!  Fixed and published to npm at `cachegoose@2.1.6`
