### ISSUE TITLE
Implement `fast-safe-stringify` instead of `JSON.stringify`

### ISSUE THREAD

**Issue by niftylettuce** [boblauer/cachegoose#42]
https://github.com/davidmarkclements/fast-safe-stringify
https://github.com/boblauer/cachegoose/blob/master/src/generate-key.js#L8

**Comment by niftylettuce** [comment]
can you explain why https://github.com/supershabam/jsosort/blob/master/index.js is used btw?

**Comment by boblauer** [comment]
In order to ensure the same query in a different order uses the same cache key.

`models.User.find({ name: 'John', age: 50 })` and
`models.User.find({ age: 50, name: 'John' })` need to generate the same cache key.

**Comment by niftylettuce** [comment]
@boblauer that makes sense, thanks.  I have another question about performance, because I feel like we can optimize this more.  I'm wondering if storing as JSON vs. storing as a String with `JSON.stringify` and then subsequently calling `JSON.parse` will yield better performance...

Specifically, can we use `hmsetbyjson` and `hmgetalljson` and drop the usage of `JSON.stringify` and `JSON.parse`?  I'm just really curious how we can optimize this more because it seems this package/Redis is the only obvious/major speed bottleneck in my application.

Ref:
- https://github.com/NodeRedis/node_redis#clienthgetallhash-callback

**Comment by niftylettuce** [comment]
Also, it is possible for us to use `hash` vs `string` here?

**Comment by boblauer** [comment]
How fast is it if you use fast-safe-stringify?
