### ISSUE TITLE
Id changing

### ISSUE THREAD

**Issue by olup** [boblauer/cachegoose#44]
How come that cached queries return proper data but changing ids ?

**Comment by boblauer** [comment]
I'm guessing something is happening on your end, the ids shouldn't change.

Can you write a simple test case that reproduces the issue?

**Comment by olup** [comment]
I am a bit under the water now, i'll make my research as soon as possible
and report. Thanks you for your quick response !

**Comment by Sytten** [comment]
I have the same problem with redis.
Any simple test will show you that the Id is not preserved.
