### ISSUE TITLE
Automatic cache invalidation

### ISSUE THREAD

**Issue by smddzcy** [boblauer/cachegoose#48]
Do you currently invalidate cache automatically when a model changes? For example:
```js
const object = await SomeModel.findOne({ foo: 'bar' }).cache(3600); // query 1
...
object.foo = 'baz';
await object.save();
// when I run query 1 again here, will I get the stale version (i.e. cached)
// or is the cache automatically invalidated?
```
If not; do you know any easy way to do it by tweaking our models/cachegoose?

**Comment by boblauer** [comment]
https://github.com/boblauer/cachegoose/blob/master/README.md#clearing-the-cache
