### ISSUE TITLE
Add support for human-readable time intervals

### ISSUE THREAD

**Issue by SerjoPepper** [boblauer/cachegoose#5]
It will be great to set time intervals in a human-readable format, ms.js can do it (https://github.com/rauchg/ms.js). Is it really to support it?

**Comment by boblauer** [comment]
I have no plans to support human-readable time intervals.  However, you could always use `ms.js` yourself, and then pass the value into the `ttl` function.  For example:

```javascript
var cacheLife = ms('1 hour') / 1000; // convert from ms to second
Record.find().cache(cacheLife);
```
