### ISSUE TITLE
.clearCache(null, cb) does not clear cache

### ISSUE THREAD

**Issue by mattdawson** [boblauer/cachegoose#50]
The docs say passing a null key should clear the cache, it doesn't.

In index.js:
module.exports.clearCache = function(customKey, cb = () => { }) {
  // if (!customKey) return cb(); // Change this line to the following to fix.
  if (!customKey) return cache.clear(cb());
  cache.del(customKey, cb);
};

**Comment by boblauer** [comment]
Thanks for opening the issue. Any chance you could open a pull request with the fix?

**Comment by mattdawson** [comment]
My apologies, not an issue, when I checked out master this was already fixed.
