### ISSUE TITLE
Feature Request :  Add Non-Cache params to function cache() function

### ISSUE THREAD

**Issue by auedbaki** [boblauer/cachegoose#53]
.cache(0, 'unique-key-delete-later') is available with two params. I'm requesting for a new param to get un-cached data from request. Like a flag - Signify rather you want to get un-cached data or not.

.cache(0, 'boolean-params') // Ket-name -> isNotCache etc.

I need it a lot in my project.

**Comment by boblauer** [comment]
I'm not sure I understand the request. If you want to get un-cached data, you can delete the cached data by using the `unique-key-delete-later` value before your next request.

Does this approach not work for you?

**Comment by auedbaki** [comment]
I'm not interested in clearing the cache.
Rather I want to use the same route endpoint to serve cache and uncached data. Just by altering a flag. This feature can reduce the common code to get same data for cached/uncached result.

**Comment by boblauer** [comment]
This is outside of the scope of what this project aims to achieve.

I would suggest wrapping these calls in a custom function that determines if the cache should be used.

```js
function getItems(shouldCache = false) {
  const query = Items.find({ someProperty: 'some value' });

  if (shouldCache) {
    query.cache(0, 'some-key');
  }

  return query.exec();
}
```
