### ISSUE TITLE
Future Performance Optimizations

### ISSUE THREAD

**Issue by niftylettuce** [boblauer/cachegoose#54]
Since #42 was closed (obviously looks like I failed to respond timely), I wanted to document issues I found with this project.

1) ~`cachegoose` uses `JSON.stringify` versus `fast-safe-stringify`~
2) `cacheman-redis` uses `redis` as opposed to `ioredis`
3) ~`cacheman-redis` uses `JSON.stringify` versus `fast-safe-stringify`~
4) ~`cachegoose` uses `jsosort`, which uses `forEach` for iterating over the keys of the object, which is incredibly slow compared to a `for` loop (ref: https://github.com/dg92/Performance-Analysis-JS, but it is widely known that `forEach` is harmful to performance)~
5) The redis command `DEL` is used as opposed to `UNLINK` for clearing cache `cachegoose.clearCache` (ref: <https://stackoverflow.com/questions/45818371/is-the-unlink-command-always-better-than-del-command>)

**Comment by niftylettuce** [comment]
I ran some local tests and `JSON.stringify` seemed to be faster for our use-case here, but `jsosort` using `forEach` versus `for` is one thing we could fix immediately.

**Comment by boblauer** [comment]
I'm curious, are these actual performance issues, or performance optimizations? In other words, have you noticed real world slowness because `cachegoose` uses `jsosort`, for example?

**Comment by niftylettuce** [comment]
Ran some more benchmarks and the difference seems negligible, however I'm sure on much larger cached results it's faster.

**Comment by niftylettuce** [comment]
The only other thing I can see is that `DEL` is blocking, and we should use `UNLINK` instead.

http://antirez.com/news/93

**Comment by aalfiann** [comment]
I have already run benchmark for node_redis and ioredis.

https://github.com/poppinlp/node_redis-vs-ioredis

and the result is
![](https://i.imgur.com/CsADcjr.png)

**Comment by aalfiann** [comment]
jsosort using for loop
```js
function jsosort(obj, sortfunction) {
  const result = {};
  const key = Object.keys(obj).sort(sortfunction);
  const keylength = key.length;
  for (let i = 0; i < keylength; i++) {
    let value = obj[key[i]];
    if (Object.prototype.toString.call(value) === '[object Object]') {
      value = jsosort(value, sortfunction);
    }
    result[key[i]] = value;
  }
  return result;
}
```

Benchmark:
[https://jsben.ch/EwBmu](https://jsben.ch/EwBmu)

If the object data is small, there is no big difference in performance and the query will always small. 
So I'm not worry about this.
