### ISSUE TITLE
Feature request: integration with Memcached or DynamoDB

### ISSUE THREAD

**Issue by GimignanoF** [boblauer/cachegoose#58]
I was looking at this package to see if I can use it in my project. I would definitively do, however it might be useful to add support for other caching targets, like Memcached or even DynamoDB. This is because I already use the [Apollo DynamoDB Cache plugin](https://www.npmjs.com/package/apollo-server-cache-dynamodb) to cache my GrahQL queries on DynamoDB and it would be nice to have also the MongoDB queries cached there, so I get full access of everything in one place (not mentioning the fact that introducing a Redis server will also add a cost to my existing architecture. Not a big one, but still measurable)

**Comment by Hyperblaster** [comment]
I'd also be very interested in exploring other caching options other than redis.
Even if there was a way or example of how to hook our own plugin into it so we can decide where to cache.

**Comment by boblauer** [comment]
To do this you'd need to create a new cacheman engine, as that's what this library uses under the hood - https://github.com/cayasso/cacheman
