### ISSUE TITLE
giving cache one query result to another one query.

### ISSUE THREAD

**Issue by sahilkhaire** [boblauer/cachegoose#59]
It is caching result and when i call same query function with change in query still it is giving first cache query result. it is not checking is that current query matches with first query or not.
It should check query and  give result as per query change.

**Comment by boblauer** [comment]
Can you please provide the two queries you are using?

**Comment by sahilkhaire** [comment]
Hi boblauer,
below is a sample code which is repleca of my code

let query  =  {_id:ObjectId(**account_id**)}
Collection1.find(query).cache(5).exec((err, data)=>{

})

so hare account_id is variable
some times i am geting data from previous query account id 
for example if i query with account_id1 and then i query with account_id2 then i got result of account_id1

**Comment by aalfiann** [comment]
yes, you can't because ObjectId(account_id) is async, so it will return undefined when cachegoose create the hash for the key.
That is why you will always get the same cache results.
