### ISSUE TITLE
Add ability to disable caching if result set is empty

### ISSUE THREAD

**Issue by rfink** [boblauer/cachegoose#6]
Would be nice to have the ability to disable caching if result set is empty.  Either on the module or the individual query level.  What are your thoughts?

**Comment by boblauer** [comment]
What is the use case? I could see it being useful caching the results of a long running query, even if the results are empty. I'm wondering why you would want to rerun the query in that scenario.

**Comment by rfink** [comment]
Well, it would be toggle-able, I would definitely not want this to be the default behavior.  My particular use case (and I've dealt with a similar use case in the past) is if you are attempting to fetch data that isn't available *yet*, or is in the middle of an update (think hitting a DB during an ETL load).

**Comment by boblauer** [comment]
You can already clear the cache manually. Could you do something like this?

```javascript
MyModel
  .find(...)
  .cache('some-unique-key')
  .exec(function(err, docs) {
    if (!docs.length) cachegoose.clearCache('some-unique-key');
  });
```

**Comment by rfink** [comment]
I think this could get close to working, except I allow the module to generate the key.  Could that be done?

**Comment by boblauer** [comment]
It can.  If you don't want to generate your own key, you can grab the auto-generated key from the `query` object.

```javascript
var query = MyModel
  .find(...)
  .cache();

query.exec(function(err, docs) {
  if (!docs.length) cachegoose.clearCache(query.getCacheKey());
});
```

**Comment by rfink** [comment]
That could work.  Thanks!  Great module BTW.  I want to create one more issue, having the ability to specify a prefix for the generated cache key.  Is that reasonable?  Should I create another issue for it?  It's one I feel I could submit a patch for myself.

**Comment by boblauer** [comment]
Thanks for the compliment!

I think specifying a prefix would be a great feature.  If you would like to submit a pull req for that, that would be awesome.

**Comment by rfink** [comment]
Absolutely, I love little helpers like this.  I created a similar one for sequelize (I may steal some of your ideas).  I'll create a parallel issue to keep this one clean.  Thanks again.
