### ISSUE TITLE
Redis connection string

### ISSUE THREAD

**Issue by harimambura** [boblauer/cachegoose#61]
Is there a way to pass redis connection string like _redis://h:p0700fe183ea2f0fea05183962c0c71b74a72fa9f7@ec2-33-222-22-177.eu-west-1.compute.amazonaws.com:23456_ ? cacheman redis could receive this as string instead of options object, but cachegoose is not

**Comment by aalfiann** [comment]
this should work
```
cachegoose(mongoose, 'redis://h:p0700fe183ea2f0fea05183962c0c71b74a72fa9f7@ec2-33-222-22-177.eu-west-1.compute.amazonaws.com:23456');
```
