### ISSUE TITLE
Occasionally create cachcache:cachegoose-cache: 

### ISSUE THREAD

**Issue by murvinlai** [boblauer/cachegoose#9]
Sometimes, it creates the cache key as:
 cachecache:cachegoose-cache:  
instead of
cache:cachegoose-cache: 

because when creating the Cacheman object, it the option.prefix is used for both option._prefix (i.e. cache:cachegoose-cache: ) and the engine (Redis) prefix.

so occasionally, in RedisClient, before issuing command, this.options.prefix is "cache", and it will append that to the agruments, which is "cache:cachegoose".

Not sure how to fix it in cachegoose or in cacheman.

**Comment by boblauer** [comment]
Can you show me what options you're passing to `cachegoose`?

**Comment by murvinlai** [comment]
var redisCacheOptions = {
    engine: 'redis',
    host: <host URL>,
    port: Number,
    password: <Password>,
    cache: true,
    ttl: 240
  }

  cachegoose(mongooseObject, redisCacheOptions);

I have tried it with prefix="". doesn't work.
if I do it with prefix="ABC", occasionally, it will have "ABCABC:cachegoose-cache:"

I think findAndUpdate causing that...

**Comment by murvinlai** [comment]
Cacheman has made an update with the prefix fix.  any idea when cachegooese will use the latest cacheman?

**Comment by boblauer** [comment]
Updated, thanks.  Published on npm `@2.1.7`
